### PR TITLE
add JedisCluster support  and add  flushInterval for  Mybatis custom caches

### PR DESCRIPTION
**Pull request by qujinqiang**
Dear, emacarron:
     I have add some future from your project, the following is a list for the new future.
     . add JedisCluster support for the caches
     . as Mybatis issue #352, do not apply decorators to custom caches. So i add a annotation to support  flushInterval for the caches
     So, i hope you can accept my pull request. At last, good luck to you!

### CODE REVIEW

**Comment by emacarron** [comment]
Thank you! Can you please add a test?

2016-01-06 11:59 GMT+01:00 qujinqiang <notifications@github.com>:

**Comment by qujinqiang** [comment]
Dear, emacarron:
   I had add flushInterval and JedisCluster test case. If you have any question,please contact me. Good luck to you!

**Comment by qujinqiang** [comment]
Dear, emacarron:
Did you see my pull request? If you have time, please check my pull request. Thank you very much!

**Comment by emacarron** [comment]
Hi. Yes, I did, but the test you added is failing with Travis. We should find a solution for that. I can think of either fixing the redis config in travis or using mocks to avoid the need to use a real redis cache for testing.

**Comment by harawata** [comment]
Closing in favor of #52 .
I've added `timeout` property.
It would be great if you could test it with the latest snapshot.

**Pull request closed without merging**
